### ISSUE TITLE
Decide how to handle logs generated by the different services

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/nlp-sandbox-infrastructure#3]
The services generating logs are:

- Orchestrator
- Data Node
- NLP Tools

The logs of the Orchestrator and the Data Node could be accessed relatively easily as these services are always up. This is tricky for NLP Tools that are evaluated as these services are up only the time needed to evaluate them.

Options are:

A. Save the log (stdout/stderr) to a folder.
B. Save the log to a service. Because the NLP Tool should not depends on external services, the Orchestrator may be responsible for querying the logs and saving them to a logging service. Maybe we could go for a solution with Logstash and Kibana to centralize the log. This would makes life easier for the staff maintaining Data Hosting Site.

**Comment by thomasyu888** [comment]
Thanks @tschaffter.  I am going to assume that the logs can't be stored to Synapse for the NLP tool similar to the EHR challenges.   For the EHR challenges we are saving the logs to stdout/stderr and there are some pros and cons to this.  

Pros: 
* Centers don't need to host a logging service and learn how to use it. 
* Current infrastructure supports this with minimal updates

Cons:
* parsing through log files on a local file system can be frustrating.

I like the idea of using a logging system to centralize the logs.  Here are some pros and cons that I think revolve around using a logging system.

Pros:
* Logging system could provide data hosting sites with a nice interface to sift through logs
* More user friendly than logs saved to a local file system.
Cons:
* Data hosting sites may not have the bandwidth to maintain a logging service
* Needs to be implemented

**Comment by tschaffter** [comment]
@thomasyu888 

> I am going to assume that the logs can't be stored to Synapse for the NLP tool similar to the EHR challenges. 

Yes, we should operate under this assumption.

Let's put together a demo that uses Logstash + Kibana. [DataDog](https://youtu.be/L1hgSKInWJU) could be an alternative. Another benefit for having a service that centralizes the logs is that they can most likely send notifications to the user (i.e. the staff maintaining Data Hosting Site), which would enable the Data Hosting Site to be more reactive towards failures.

Centralizing log has a low priority but down the road I totally see us putting this in place.

**Comment by tschaffter** [comment]
@thomasyu888 This repository provides everything required to run the ELK Stack (Elasticsearch, Logstash and Kibana):
https://github.com/Sage-Bionetworks/nlp-sandbox-elk

The top section of the README describes how to deploy the stack and access Kibana (dashboard).

![elk_1](https://user-images.githubusercontent.com/3056480/95681243-92726280-0b93-11eb-9301-c837119feb60.png)

![elk_3](https://user-images.githubusercontent.com/3056480/95681249-9900da00-0b93-11eb-9c85-e48075ceb681.png)

![elk_4](https://user-images.githubusercontent.com/3056480/95681255-9e5e2480-0b93-11eb-8182-ab7f9eb79dd2.png)

![elk_5](https://user-images.githubusercontent.com/3056480/95681256-a1591500-0b93-11eb-89d8-a4b744919dea.png)

## Shipping data into the ELK Stack

We could use [Filebeat](https://elk-docker.readthedocs.io/#forwarding-logs-filebeat) to push host logs to the stack. The version of Filebeat used must match the version of the ELK stack (see Filebeat link). A potential issue with Filebeat is that it requires to be installed on the host(s) while we may prefer relying only on dockerized service.

**Comment by thomasyu888** [comment]
Posting this here as relevant. https://www.google.com/amp/s/logz.io/blog/docker-logging/amp/

**Comment by thomasyu888** [comment]
I do think it's important to note that the more services we add, the more complex it is for data hosting sites in the future.  There are some sites that can't use docker compose which would increase the complexity of this by a bit.

**Comment by tschaffter** [comment]
It's an important note, thanks! It's up to each Data Hosting Site to identify the monitoring strategy that works for it. Because we are responsible of the Sage Data Hosting Site we can afford to use ELK to make our work comfortable. :)

**Comment by thomasyu888** [comment]
Actually, we should just use the logspout extension: https://github.com/deviantony/docker-elk/tree/master/extensions/logspout

**Comment by tschaffter** [comment]
Why is that?

**Comment by tschaffter** [comment]
Oh, that's the extension you identified last week. Sounds good!

**Comment by tschaffter** [comment]
Let's give a shot to ELK + logspout. The implementation will be tracked in a separate ticket.
